version: 0.2
phases:
  install:
    runtime-versions:
      java: amazoncorretto:11
  pre_build:
    commands:
      - echo In the pre_build phase...
      - cd app && mvn clean install # Creates a jar file
      - aws --version
      - ECR_REPO="416068129208.dkr.ecr.us-east-1.amazonaws.com/digimonapi"
      - $(aws ecr get-login --no-include-email --region us-east-1) # Login to AWS ECR
  build:
    commands:
      - echo Build started on `date`
      - docker build -t digimonapi .
      - docker tag digimonapi:latest $ECR_REPO:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $ECR_REPO:latest
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml

cache:
  paths:
    - '/root/.m2/**/*' # Caches maven dependencies for a quicker build