AWSTemplateFormatVersion: 2010-09-09
Description: ECS Fargate Template

Parameters:
  DesiredNumberOfTasks:
    Description: Number of tasks to launch for the service
    Type: Number
    Default: 1
    MinValue: 1
  MinNumberOfTasks:
    Description: Minimum number of tasks to launch for the service
    Type: Number
    Default: 1
    MinValue: 0
  MaxNumberOfTasks:
    Description: Maximum number of tasks to launch for the service
    Type: Number
    Default: 2
    MinValue: 0    
  ListenerContainerPort:
    Description: Listening port for container
    Type: Number
    Default: 80
  ContainerName: 
    Description: Container Name
    Type: String
    Default: 'digimonapi'
  ContainerCpu:
    Description: The number of cpu units reserved for the container.
    Type: Number
    Default: 256
  ContainerMemory:
    Description: The amount (in MiB) of memory to present to the container.
    Type: Number
    Default: 512
  ContainerMemoryReservation:
    Description: The soft limit (in MiB) of memory to reserve for the container.
    Type: Number
    Default: 512
  FeatureName:
    Description: Nome da feature
    Type:  String
    Default: 'springboot'
  MicroServiceName:
    Description: Nome do micro servico
    Type:  String
    Default: 'digimonapi'
  DevToolsAccount:
    Type: Number
    Default: 416068129208
  Environment:
    Type: String
    Default: dev
  EcsClusterName:
    Description: Name of the ECS Cluster
    Type: String 
    Default: 'digimon-cluster'
  VPCID:
    Description: ID da VPC
    Type:  AWS::EC2::VPC::Id
  VPCCIDR:
    Description: CIDR da VPC para configuracao do SG dos servicos
    Type:  String
    Default: '0.0.0.0/0'
  PrivateSubnets:
    Type:  List<AWS::EC2::Subnet::Id>    
  SecurityGroupDefault: 
    Description: 'Securtity Group Default da Conta'
    Type: AWS::EC2::SecurityGroup::Id
  LoadBalancingCrossZoneEnabled:
    Description: 'Enable Load Balancer Cross Zone'
    Type: String
    Default: 'false'
    AllowedValues: [ 'true', 'false' ]
  EnvironmentMachine:
    Description: Variaveis de ambiente da maquina
    Type: String

Resources:
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${FeatureName}-${MicroServiceName}"
      RetentionInDays: 7

  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Name: !Sub ${ContainerName}
          Image: '416068129208.dkr.ecr.us-east-1.amazonaws.com/digimonapi:latest'
          PortMappings:
            - ContainerPort: !Ref ListenerContainerPort
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          MemoryReservation: !Ref ContainerMemoryReservation
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Sub "${AWS::Region}"
              awslogs-group: !Sub "${FeatureName}-${MicroServiceName}"
              awslogs-stream-prefix: !Sub "${FeatureName}-${MicroServiceName}"
      Family: !Sub "family-${FeatureName}-${MicroServiceName}"
      NetworkMode: awsvpc
      Memory: !Ref ContainerMemoryReservation
      Cpu: !Ref ContainerCpu
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !Ref TaskExecutionRole
      RequiresCompatibilities:
        - "FARGATE"
    DependsOn: CloudWatchLogGroup

  ## For Fargate
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: !Sub "${FeatureName}-${MicroServiceName}-AmazonECSTaskExecutionRolePolicy"
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  # Allow the ECS Tasks to download images from ECR
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                  # Allow the ECS tasks to upload logs to CloudWatch
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogStreams'
                Resource: '*'
        - PolicyName: !Sub "${FeatureName}-${MicroServiceName}-ECS"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecs:DiscoverPollEndpoint'
                  - 'ecs:RegisterContainerInstance'
                  - 'ecs:SubmitContainerStateChange'
                  - 'ecs:SubmitTaskStateChange'
                  - 'ecs:ListContainerInstances'
                  - 'ecs:Poll'
                  - 'ecs:StartTelemetrySession'
                  - 'ecs:UpdateContainerInstancesState'
                  - 'ecs:ListTasks'
                  - 'ecs:DescribeContainerInstances'
                Resource: '*'
        - PolicyName: !Sub "${FeatureName}-${MicroServiceName}-passrole"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:container-instance/*'
        - PolicyName: !Sub "${FeatureName}-${MicroServiceName}-passrole-2"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${EcsClusterName}'
        - PolicyName: !Sub '${FeatureName}-${MicroServiceName}-cloudwatch'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:PutMetricData'
                Resource: '*'

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub '${AWS::StackName}'
      GroupDescription: 'nlb-digimon-api'
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          Description: 'Conexao com o NLB'
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref VPCCIDR
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: 'Saida para todas as portas'
          IpProtocol: "-1"
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}'

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ListenerContainerPort
      Protocol: TCP
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: '/actuator/health'
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 6
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: '200-399'
      VpcId: !Ref VPCID
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '5'
      TargetType: ip

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub 'nlb-${MicroServiceName}'
      Type: network
      Scheme: internal
      LoadBalancerAttributes:
        - Key: 'load_balancing.cross_zone.enabled'
          Value: !Ref LoadBalancingCrossZoneEnabled
      Subnets: !Ref PrivateSubnets
      Tags:
        - Key: LoadBalancerType
          Value: VPCLink

  DigimonVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Description: "VpcLink Digimon"
      Name: !Sub "${MicroServiceName}-vpc-link"
      TargetArns:
        - !Ref LoadBalancer

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: LoadBalancer
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref ListenerContainerPort
      Protocol: TCP

  Service:
    DependsOn: Listener
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Sub service-${FeatureName}-${MicroServiceName}
      Cluster: !Ref EcsClusterName
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: !Ref DesiredNumberOfTasks
      HealthCheckGracePeriodSeconds: 10
      LaunchType: FARGATE
      PlatformVersion: '1.4.0'
      LoadBalancers:
        - ContainerName: !Sub ${ContainerName}
          ContainerPort: !Ref ListenerContainerPort
          TargetGroupArn: !Ref TargetGroup
      SchedulingStrategy: REPLICA
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SecurityGroupDefault
            - !Ref SecurityGroup
          Subnets: !Ref PrivateSubnets

  ScalingRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action: ["sts:AssumeRole"]
      Policies:
        - PolicyName: adjust-service-desired-count
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: ecs:UpdateService
                Resource: !Ref Service

  ScalableTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties:
      MinCapacity: !Ref MinNumberOfTasks
      MaxCapacity: !Ref MaxNumberOfTasks
      ResourceId: !Join
        - "/"
        - - service
          - !Ref EcsClusterName
          - !GetAtt Service.Name
      RoleARN: !GetAtt ScalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: ScaleWithCpu
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 20
        ScaleInCooldown: 120
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
